  const dashboard = await read('components/academy/academy-dashboard.tsx')
  assert.match(dashboard, /const flushProgress = \(\) => \{\n      const snapshot = progressRef\.current/)
  assert.match(dashboard, /const flushWhenHidden = \(\) => \{\n      if \(document\.visibilityState === 'hidden'\) flushProgress\(\)/)
  assert.match(dashboard, /window\.addEventListener\('pagehide', flushProgress\)/)
  assert.match(dashboard, /document\.addEventListener\('visibilitychange', flushWhenHidden\)/)
  assert.match(dashboard, /window\.removeEventListener\('pagehide', flushProgress\)/)
  assert.match(dashboard, /document\.removeEventListener\('visibilitychange', flushWhenHidden\)/)
  assert.match(dashboard, /persistProgress\(\{\n        activeLessonId: snapshot\.activeLessonId,[\s\S]*?codeByLesson: snapshot\.codeByLesson,/)
})

test('Academy describes its current deterministic verification model accurately', async () => {
  const dashboard = await read('components/academy/academy-dashboard.tsx')
  assert.match(dashboard, /Every lesson is verified against a deterministic\s+assertion engine\./)
  assert.doesNotMatch(dashboard, /Every lesson is verified against a live\s+assertion engine\./)
})

test('Academy syllabus exposes keyboard-friendly semantic controls and locked-lesson context', async () => {
  const syllabus = await read('components/academy/syllabus-tree.tsx')
  assert.match(syllabus, /<nav aria-label="Course syllabus"/)
  assert.match(syllabus, /<button[\s\S]*?type="button"[\s\S]*?aria-expanded=\{isOpen\}[\s\S]*?aria-controls=\{lessonListId\}/)
  assert.match(syllabus, /<ul id=\{lessonListId\}/)
  assert.doesNotMatch(syllabus, /disabled=\{!unlocked\}/)
  assert.match(syllabus, /aria-disabled=\{!unlocked\}/)
  assert.match(syllabus, /aria-current=\{active \? 'true' : undefined\}/)
  assert.match(syllabus, /aria-label=\{unlocked \? lesson\.title : `\$\{lesson\.title\}\. \$\{lockedReason\}`\}/)
  assert.match(syllabus, /Complete “\$\{prerequisiteTitle\}” to unlock this lesson/)
  assert.match(syllabus, /focus-visible:outline-primary/)
})

test('Academy lesson workspace exposes uniquely associated editor and live verification output', async () => {
  const workspace = await read('components/academy/lesson-workspace.tsx')
  assert.match(workspace, /const editorId = `code-editor-\$\{lesson\.id\}`/)
  assert.match(workspace, /const requirementsId = `verification-requirements-\$\{lesson\.id\}`/)
  assert.match(workspace, /const outputId = `verification-output-\$\{lesson\.id\}`/)
  assert.match(workspace, /<label htmlFor=\{editorId\}/)
  assert.match(workspace, /id=\{editorId\}/)
  assert.match(workspace, /aria-describedby=\{`\$\{requirementsId\} \$\{outputId\}`\}/)
  assert.match(workspace, /id=\{requirementsId\}/)
  assert.match(workspace, /id=\{outputId\}/)
  assert.match(workspace, /role="log" aria-live="polite"/)
  assert.match(workspace, /aria-busy=\{running\}/)
  assert.match(workspace, /focus-visible:ring-primary\/70/)
  assert.match(workspace, /focus-visible:outline-primary/)
  assert.match(workspace, /role="status"[\s\S]*?aria-live="polite"[\s\S]*?>\s*Completed/)
})
