'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useState } from 'react';
import { Play, RotateCcw, Lightbulb, CheckCircle2, Terminal } from 'lucide-react';
import { ZenithShell } from '@/components/zenith-shell';
import { course } from '@/lib/zenith-data';
const Editor=dynamic(()=>import('@monaco-editor/react'),{ssr:false,loading:()=> <div style={{padding:20}} className="muted">Loading Monaco…</div>});
export default function Learn(){const lesson=course.chapters[0].lessons[0];const [code,setCode]=useState(lesson.starter);const [output,setOutput]=useState('Ready. Submit code to the execution service when configured.');const [choice,setChoice]=useState('');return <ZenithShell><div className="lab"><section className="lesson"><div className="eyebrow">Chapter 1 · Mental Models of Programs</div><h1>{lesson.title}</h1><p className="muted">Concept: Variables · foundational</p><div className="lesson-block"><strong>Problem</strong><br/>{lesson.body}</div><div className="lesson-block"><strong>Mental model</strong><br/>Think in terms of bindings and values. The syntax is only the surface representation of the language semantics.</div><div className="lesson-block"><strong>Technical definition</strong><br/>A variable is a language-defined binding between an identifier and a value or storage location.</div><div className="quiz"><strong>Concept check</strong><p>{lesson.question}</p>{['The identifier changes.','The binding stays named x, but its associated value changes.','Both the identifier and value change.'].map(x=><button key={x} className={'option '+(choice===x?'selected':'')} onClick={()=>setChoice(x)}>{x}</button>)}{choice&&<div style={{marginTop:12,color:choice=== 'The binding stays named x, but its associated value changes.'?'var(--accent)':'var(--danger)'}}>{choice=== 'The binding stays named x, but its associated value changes.'?'Correct. This creates learning evidence.':'Not quite. Recall the binding/value distinction and try again.'}</div>}</div></section><section className="editor"><div className="editor-head"><span className="mono">main.ts</span><div className="editor-actions"><button className="btn" onClick={()=>setCode(lesson.starter)}><RotateCcw size={13}/>Reset</button><button className="btn" onClick={()=>setOutput('Execution request queued. Configure EXECUTION_SERVICE_URL for real sandbox execution.')}><Play size={13}/>Run</button><button className="btn"><Lightbulb size={13}/>Hint</button></div></div><Editor height="calc(100vh - 318px)" defaultLanguage="typescript" theme="vs-dark" value={code} onChange={v=>setCode(v??'')} options={{fontSize:14,minimap:{enabled:false},padding:{top:16},automaticLayout:true}}/><div className="terminal"><div style={{color:'var(--accent)',marginBottom:8}}><Terminal size={13} style={{verticalAlign:'middle'}}/> TERMINAL</div><div>{output}</div><div style={{marginTop:12}}>$ zenith test --submission</div><div className="muted">Protected progression is awarded only after server-side execution + test verification.</div></div></section></div></ZenithShell>}
